language: cpp

compiler:
  - gcc

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE-Release ..
  - make
  - make backend_tests engine_tests
  - ./backend/tests/backend_tests
  - ./engine/tests/engine_tests
