language: cpp

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi

install:
  # libtorch (for neural networks)
  - wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.4.0%2Bcpu.zip
  - unzip libtorch-cxx11-abi-shared-with-deps-1.4.0%2Bcpu.zip
  # mio (for memory-mapped opening books)
  - git clone https://github.com/mandreyel/mio
  - cd mio && mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ..
  - sudo make install
  - cd ../..

script:
  - mkdir build && cd build
  - cmake -DTorch_DIR=$(pwd)/../libtorch/share/cmake/Torch -DCMAKE_BUILD_TYPE=Release ..
  - make all
  - ./backend/tests/backend_tests
  - ./engine/tests/engine_tests
