language: cpp

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi

install:
  # libtorch (for neural networks)
  - wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.4.0%2Bcpu.zip
  - unzip libtorch-cxx11-abi-shared-with-deps-1.4.0+cpu.zip


script:
  - mkdir build && cd build
  - cmake -DTorch_DIR=$(pwd)/../libtorch/share/cmake/Torch -DCMAKE_BUILD_TYPE=Release ..
  - make all
  - ./tests/backend/backend_tests
  - ./tests/engine/engine_tests
