os: linux
dist: trusty
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
      - gcc-8
      - g++-8
      - cmake

before_install:
  - apt remove cmake
  - pip install cmake --upgrade
  - export CC=gcc-8
  - export CXX=g++-8
  - cmake --version

install:
  # libtorch (for neural networks)
  - wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.4.0%2Bcpu.zip
  - unzip libtorch-cxx11-abi-shared-with-deps-1.4.0+cpu.zip


script:
  - mkdir build && cd build
  - cmake -DTorch_DIR=$(pwd)/../libtorch/share/cmake/Torch -DCMAKE_BUILD_TYPE=Release ..
  - make all
  - ./tests/backend/backend_tests
  - ./tests/engine/engine_tests
