os: linux
dist: trusty
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
      - gcc-8
      - g++-8

before_install:
  - export CC=gcc-8
  - export CXX=g++-8

install:
  # Latest cmake -- see https://riptutorial.com/cmake/example/4723/configure-travis-ci-with-newest-cmake
  - sudo apt remove cmake
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.17.0/cmake-3.17.0-Linux-x86_64.tar.gz
  - tar -xvf cmake-3.17.0-Linux-x86_64.tar.gz
  - mv cmake-3.17.0-Linux-x86_64.tar.gz cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}
  # libtorch (for neural networks)
  - wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.4.0%2Bcpu.zip
  - unzip libtorch-cxx11-abi-shared-with-deps-1.4.0+cpu.zip


script:
  - mkdir build && cd build
  - cmake -DTorch_DIR=$(pwd)/../libtorch/share/cmake/Torch -DCMAKE_BUILD_TYPE=Release ..
  - make all
  - ./tests/backend/backend_tests
  - ./tests/engine/engine_tests
